# Generated by Django 2.2.5 on 2019-10-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='File',
        ),
    ]
